spring.application.name=backend

spring.datasource.url=jdbc:postgresql://dpg-d6nsunh4tr6s73ca0f1g-a/todo_db_v8x4
spring.datasource.username=todo_db_v8x4_user
spring.datasource.password=RPtfru9mzKkwn0fGdX6zbyhDE3dIwPIa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
jwt.secret=${JWT_SECRET}
JWT_SECRET=todoApp@Aryan#SecretKey2026$Render!Backend